# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./main.go"
bin = "./tmp/main"
include_ext = ["go"] # With this line, it only watches .go files
exclude_dir = ["tmp", "vendor", "node_modules"]
delay = 1000 # milliseconds

[log]
time = true

[misc]
clean_on_exit = true
